"$schema" = 'https://starship.rs/config-schema.json'

# format = """\
# [](bg:#030B16 fg:#FF9E3B)\
# [󰀵 ](bg:#FF9E3B fg:#090c0c)\
# [](fg:#FF9E3B bg:#C4B28A)\
# $time\
# [](fg:#C4B28A bg:#8EA4A2)\
# $directory\
# [](fg:#8EA4A2 bg:#C4B28A)\
# $git_branch\
# $git_status\
# $git_metrics\
# [](fg:#C4B28A bg:#030B16)\
# $gcloud\
# """

# format = """\
# [](bg:none fg:love)\
# [ ](bg:love fg:base)\
# [](fg:love bg:rose)\
# $time\
# [](fg:rose bg:gold)\
# $directory\
# [](fg:gold bg:rose)\
# $git_branch\
# $git_status\
# $git_metrics\
# [](fg:rose bg:none)\
# $all
# """

format = """\
[](bg:none fg:bright_orange)\
[ ](bg:bright_orange fg:background)\
[](fg:bright_orange bg:accent_foreground)\
$time\
[](fg:accent_foreground bg:dim_foreground)\
$directory\
[](fg:dim_foreground bg:foreground)\
$git_branch\
$git_status\
$git_metrics\
[](fg:foreground bg:none)\
$all
"""

palette = 'kanagawa'

[palettes.rosepine]
base = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
gold = "#f6c177"
rose = "#ebbcba"
pine = "#31748f"
foam = "#9ccfd8"
iris = "#c4a7e7"
highlightlow = "#21202e"
highlightmed = "#403d52"
highlighthigh = "#524f67"



# Kanagawa Dragon Colorscheme Palette
[palettes.kanagawa]
background = "#1a1a22"
dimmer_background = "#16161d"
lighter_background = "#2b2a33"
foreground = "#dcd7ba"
dim_foreground = "#6f7577"
accent_foreground = "#c8c093"
red = "#c34043"
orange = "#ffa066"
bright_orange = "#FF9E3B"
yellow = "#dca561"
green = "#76946a"
blue = "#658594"
purple = "#938aa9"
teal = "#6a9589"
gray = "#727169"
light_gray = "#c0c0c0"
dark_gray = "#4e4f67"
wave_blue = "#223249"
storm_gray = "#363646"
peach_orange = "#fa9b61"
autumn_red = "#e82424"
sakura_pink = "#d27e99"
samurai_red = "#d93850"

[palettes.nord]
base = '#2E3440'
nord1 = '#3B4252'
nord2 = '#434C5E'
nord3 = '#4C566A'
muted = '#D8DEE9'
nord7 = '#8FBCBB'
nord8 = '#88C0D0'
iris = '#81A1C1'
rose = '#5E81AC'
nord11 = '#BF616A'
nord13 = '#EBCB8B'
nord14 = '#A2BE8A'
love = '#B48EAD'
bright-white = '#D8DEE9'

[directory]
format = "[   $path ]($style)"
style = "fg:background bg:dim_foreground"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:background bg:foreground"

[git_status]
format = '[$all_status]($style)'
style = "fg:background bg:foreground"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:background bg:foreground"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[ ➜](bold love) '
error_symbol = '[ ✗](pine) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:accent_foreground"
format = '[[ 󱑍 $time ](bg:accent_foreground fg:background)]($style)'

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[bun]
format = '\[[$symbol($version)]($style)\]'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'

[crystal]
format = '\[[$symbol($version)]($style)\]'

[daml]
format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[$symbol($version)]($style)\]'

[erlang]
format = '\[[$symbol($version)]($style)\]'

[fennel]
format = '\[[$symbol($version)]($style)\]'

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'


[golang]
format = '\[[$symbol($version)]($style)\]'

[gradle]
format = '\[[$symbol($version)]($style)\]'

[guix_shell]
format = '\[[$symbol]($style)\]'

[haskell]
format = '\[[$symbol($version)]($style)\]'

[haxe]
format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[java]
format = '\[[$symbol($version)]($style)\]'

[julia]
format = '\[[$symbol($version)]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
format = '\[[$symbol$project]($style)\]'

[nim]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
format = '\[[$symbol($version)]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
format = '\[[$symbol]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[perl]
format = '\[[$symbol($version)]($style)\]'

[php]
format = '\[[$symbol($version)]($style)\]'

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[scala]
format = '\[[$symbol($version)]($style)\]'

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[swift]
format = '\[[$symbol($version)]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'

[solidity]
format = '\[[$symbol($version)]($style)\]'

