format = """\
[](bg:#030B16 fg:#FF9E3B)\
[󰀵 ](bg:#FF9E3B fg:#090c0c)\
[](fg:#FF9E3B bg:#C4B28A)\
$time\
[](fg:#C4B28A bg:#8EA4A2)\
$directory\
[](fg:#8EA4A2 bg:#C4B28A)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#C4B28A bg:#030B16)\
$character\
"""

[directory]
format = "[   $path ]($style)"
style = "fg:#1C3A5E bg:#8EA4A2"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#1C3A5E bg:#C4B28A"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#C4B28A"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#C4B28A"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#E84D44) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#C4B28A"
format = '[[ 󱑍 $time ](bg:#C4B28A fg:#1C3A5E)]($style)'
