# Start AeroSpace at login
start-at-login = true

# Normalization settings
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Accordion layout settings
accordion-padding = 30

# Default root container settings
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus settings
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Automatically unhide macOS hidden apps
automatically-unhide-macos-hidden-apps = true

# Key mapping preset
[key-mapping]
preset = 'qwerty'

# Gaps settings
[gaps]
inner.horizontal = 6
inner.vertical =   6
outer.left =       6
outer.bottom =     6
outer.top =        42
outer.right =      6

# Main mode bindings
[mode.main.binding]
# Launch applications
alt-shift-cmd-ctrl-n = 'exec-and-forget open -na "Neovide"'
alt-shift-cmd-ctrl-t = 'exec-and-forget open -na "Kitty"'

# Window management
cmd-w = "close"
alt-shift-cmd-ctrl-slash = 'layout tiles horizontal vertical'
alt-shift-cmd-ctrl-comma = 'layout accordion horizontal vertical'
alt-shift-cmd-ctrl-m = 'fullscreen'

# Focus movement
alt-shift-cmd-ctrl-h = 'focus left'
alt-shift-cmd-ctrl-j = 'focus down'
alt-shift-cmd-ctrl--k = 'focus up'
alt-shift-cmd-ctrl--l = 'focus right'

# Window movement
shift-cmd-h = 'move left'
shift-cmd-j = 'move down'
shift-cmd-k = 'move up'
shift-cmd-l = 'move right'

# Resize windows
alt-shift-cmd-ctrl-minus = 'resize smart -50'
alt-shift-cmd-ctrl-equal = 'resize smart +50'

# Workspace management
alt-cmd-1 = 'workspace 1'
alt-cmd-2 = 'workspace 2'
alt-cmd-3 = 'workspace 3'
alt-cmd-4 = 'workspace 4'
alt-cmd-5 = 'workspace 5'
alt-cmd-6 = 'workspace 6'
alt-cmd-7 = 'workspace 7'
alt-cmd-8 = 'workspace 8'
alt-cmd-9 = 'workspace 9'

# Move windows to workspaces
shift-cmd-1 = 'move-node-to-workspace 1'
shift-cmd-2 = 'move-node-to-workspace 2'
shift-cmd-3 = 'move-node-to-workspace 3'
shift-cmd-4 = 'move-node-to-workspace 4'
shift-cmd-5 = 'move-node-to-workspace 5'
shift-cmd-6 = 'move-node-to-workspace 6'
shift-cmd-7 = 'move-node-to-workspace 7'
shift-cmd-8 = 'move-node-to-workspace 8'
shift-cmd-9 = 'move-node-to-workspace 9'

# Workspace navigation
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Enter service mode
alt-shift-cmd-ctrl-v = 'mode service'

# Service mode bindings
[mode.service.binding]
# Reload config and exit service mode
esc = ['reload-config', 'mode main']

# Reset layout
r = ['flatten-workspace-tree', 'mode main']

# Toggle floating/tiling layout
f = ['layout floating tiling', 'mode main']

# Close all windows but current
backspace = ['close-all-windows-but-current', 'mode main']

# Join with adjacent windows
shift-cmd-h = ['join-with left', 'mode main']
shift-cmd-j = ['join-with down', 'mode main']
shift-cmd-k = ['join-with up', 'mode main']
shift-cmd-l = ['join-with right', 'mode main']

# Window detection rules
[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.apple.Mail'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'im.beeper'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.neovide.neovide'
run = 'move-node-to-workspace 1'
